name: Crypto AI Agent 2026
on:
  schedule:
    - cron: '*/20 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Update ke v4
      - name: Set up Python
        uses: actions/setup-python@v5 # Update ke v5
        with:
          python-version: '3.11' # Upgrade ke Python 3.11
      - name: Install dependencies
        run: pip install ccxt google-genai aiohttp # Ganti ke google-genai
      - name: Run Bot
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python bot.py
